import{S as p,i as a}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&t(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();function m(i){return fetch(`https://pixabay.com/api/?q=${i}&image_type=photo&orientation=horizontal&safesearch=true&key=47395064-b7fd47e3542f1aea6492dfd3a`).then(t=>{if(!t.ok)throw new Error(t.statusText);return t.json()})}function d(i){return i.map(({webformatURL:r,largeImageURL:n,tags:t,likes:e,views:s,comments:o,downloads:u})=>`<li class="list-item" >
  <a href="${n}" alt="${t}" title=""/>
    <img src="${r}" alt="${t}" class="img-item">
  <div class="list-container">
  <p class="item"><span class="item-text">Likes</span> <span>${e}</span></p>
  <p class="item"><span class="item-text">Wiews</span> <span>${s}</span></p>
  <p class="item"><span class="item-text">Comments</span> <span>${o}</span></p>
  <p class="item"><span class="item-text">Downlods</span> <span>${u}</span></p>
  </div></a>
</li>`).join("")}const f=new p(".list-js a",{captionsData:"alt",captionDelay:250,captionClass:"imageTitle"}),h=document.querySelector(".form-js"),l=document.querySelector(".list-js"),c=document.querySelector(".loader");h.addEventListener("submit",g);function g(i){i.preventDefault();const{picture:r}=i.target.elements,n=r.value.trim();if(l.innerHTML="",!n){a.error({title:"Error",message:"Please enter a valid search query!",position:"center"});return}c.classList.remove("hidden"),m(n).then(t=>{if(c.classList.add("hidden"),!t.hits.length){a.warning({title:"No Results",message:"No images match your search. Please try another keyword!",position:"center"});return}l.innerHTML=d(t.hits),f.refresh()}).catch(t=>{c.classList.add("hidden"),a.error({title:"Error",message:`Something went wrong: ${t.message}. Please try again later.`,position:"center"}),console.error("Error fetching images:",t)}).finally(()=>{r.value=""})}
//# sourceMappingURL=index.js.map
